# Generated by Django 4.2.7 on 2023-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documento_name_alter_documento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='name',
            field=models.CharField(default='Funcionarios', max_length=30),
        ),
    ]
