# Generated by Django 4.2.7 on 2023-11-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_documento_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='uploaded_at',
            new_name='data_upload',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='name',
            new_name='nome',
        ),
    ]
