# Generated by Django 4.2.7 on 2023-11-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_uploaded_at_documento_data_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='home.tipocontrato'),
        ),
    ]
